version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goitom-finance-app
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=goitom_finance
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - CACHE_DRIVER=file
      - SESSION_DRIVER=database
      - QUEUE_CONNECTION=database
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    depends_on:
      - db
      - redis
    networks:
      - goitom-network

  db:
    image: postgres:17-alpine
    container_name: goitom-finance-db
    environment:
      - POSTGRES_DB=goitom_finance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - goitom-network

  redis:
    image: redis:7-alpine
    container_name: goitom-finance-redis
    ports:
      - "6379:6379"
    networks:
      - goitom-network

volumes:
  postgres_data:

networks:
  goitom-network:
    driver: bridge

