[providers]
php = "^8.3"
composer = true

[phases.setup]
nixpkgs = []
aptPackages = ["libicu-dev", "zlib1g-dev", "libpng-dev", "libjpeg-dev", "libfreetype6-dev"]
commands = [
  "docker-php-ext-install intl zip",
  "docker-php-ext-configure gd --with-freetype --with-jpeg",
  "docker-php-ext-install gd"
]

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-dev --no-interaction --ignore-platform-req=ext-intl --ignore-platform-req=ext-zip"
]

[phases.build]
cmds = []

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

